name: CI
on: [pull_request]

env:
  GO_VERSION: '1.21'

jobs:
  linters:
    name: Linters
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install vendors
        run: make deps

      - name: Run golangci-lint
        run: make lint

  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: 1.21
          cache: true

      - name: Install vendors
        run: make deps

      - name: Tests
        run: make tests
